pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scmGit(branches: [[name: '*/feature1']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/savi7012/Cloud-DevOps.git']])
            }
        }
        
        stage('Run') {
            steps {
                sh 'python3 git/main.py 1 2 3'
            }
        }
        
      
    }
}
