pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scmGit(branches: [[name: '*/feature1']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/savi7012/Cloud-DevOps.git']])
            }
        }
        
        stage('Run') {
            steps {
                sh 'python3 git/main.py 1 2 3'
            }
        }

        stage('Build') {
            steps {
                sh 'curl -uAdmin:Admin@123 -T /var/jenkins_home/workspace/Python-Project/git/main.py "http://localhost:8082/artifactory/python-exe-1/main.py"'
            }
        }
        
      
    }
}
